<div>
    <?php
    $form = $this->form;
    $form->prepare();
    ?>

    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formHidden($form->get('id')); ?>
    <div class="form_row">
        <?php echo $this->formRow($form->get('name')); ?>
    </div>
    <div class="form_row">
        <?php echo $this->formRow($form->get('author')); ?>
    </div>
    <div class="form_row">
        <?php echo $this->formRow($form->get('title')); ?>
    </div>
    <div class="form_row">
        <?php echo $this->formRow($form->get('lyrics')); ?>
        <div class="textarea_select_editor textarea_select_editor_text">
            <a class="no_href" href="javascript:void(0);" onclick="WebEditor.ckEditorInit('#lyrics', '.textarea_select_editor_text');">CKEditor</a>
            <a class="no_href" href="javascript:void(0);" onclick="WebEditor.tinyMceInit('#lyrics', '.textarea_select_editor_text');">TinyMCE</a>
        </div>
    </div>
    <div class="form_row">
        <?php echo $this->formRow($form->get('file')); ?>
    </div>
    <div class="form_row">
        <?php echo $this->formRow($form->get('file2')); ?>
    </div>
    <div class="form_row">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>