<?php
$title = $this->translate('Software');
$this->headTitle($title);
?>

<div id="container">
    <div id="content">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        
        <div>
            <?php echo $this->partialLoop('software/software/index-item.phtml', $this->paginator) ?>
        </div>
        
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml', array('route' => 'software')); ?>
    </div><!-- #content-->
</div><!-- #container-->

<?php echo $this->sideLeftSoftware(); ?>
