<?php
$title = $item->title . ' ' . $item->version;
$this->headTitle($title . ' - ' . $this->translate('Software'));
?>

<div id="container">
    <div id="content">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <div style="margin-bottom: 20px;">
            <strong><?php echo $this->translate('Author') ?></strong>: <?php echo $this->escapeHtml($item->authorTitle); ?>
        </div>

        <div>
            <?php echo $item->text; ?>
        </div>
        
        <?php if (!empty($item->file)) { ?>
            <div>
                <a class="download_link" href="<?php echo $this->basePath(); ?>/upload/software/files/<?php echo $item->file; ?>">Скачать</a>
            </div>
        <?php } ?>

        <div style="margin-top: 20px; background: #F9FAFA; border: 1px solid #ccc; border-radius: 5px;">
            <div style="float: right;">
                <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
                <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter"></div> 
            </div>
            <div class="clr"></div>
        </div>
        
        <div style="margin-top: 40px;">
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                var disqus_shortname = 'jhekasoft'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
        </div>
    </div><!-- #content-->
</div><!-- #container-->

<?php echo $this->sideLeft(); ?>
