<?php
$title = $item->title . ' ' . $item->version;
$this->headTitle($title . ' - ' . $this->translate('Software'));
?>

<div id="container">
    <div id="content">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <div>
            <?php echo $this->translate('Author') ?>: <?php echo $item->author; ?>
        </div>

        <div>
            <?php echo $item->text; ?>
        </div>
    </div><!-- #content-->
</div><!-- #container-->

<?php echo $this->sideLeft(); ?>
