<?php echo $this->doctype(); ?>
<html>
<head>
    <meta charset="utf-8" />
    <?php echo $this->headTitle($this->translate('Jhekasoft personal site'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/style.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/functions.js')
                                  ->prependFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'IE',))
                                  ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js') ?>

    <script>
        $(window).load(function() {
            $('#sideLeft').css('height', $('#content').outerHeight() + 20)
        });
        
        $(window).resize(function() {
            $('#sideLeft').css('height', $('#content').outerHeight() + 20)
        });
    </script>
    
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35700833-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
</head>

<body>

    <div id="wrapper">

        <header id="header">
            <div class="nav_block">
                <nav class="nav_block_main">
                    <div class="nav_block_logo">
                        <a href="<?php echo $this->url('home'); ?>" class="nav_block_logo_link">Jhekasoft</a>
                    </div>
                    <ul class="nav_block_main_menu">
                        <li>
                            <a href="<?php echo $this->url('software'); ?>"><?php echo $this->translate('Software'); ?></a>
                        </li>
                        <li>
                            <a href="#"><?php echo $this->translate('Games'); ?></a>
                        </li>
                        <li>
                            <a href="#"><?php echo $this->translate('Video'); ?></a>
                        </li>
                        <li>
                            <a href="#"><?php echo $this->translate('Sound'); ?></a>
                        </li>
                        <li>
                            <a href="#"><?php echo $this->translate('Blog'); ?></a>
                        </li>
                        <li>
                            <a href="#"><?php echo $this->translate('About'); ?></a>
                        </li>
                        <li class="nav_block_main_menu_end">
                            <span>&nbsp;</span>
                        </li>
                    </ul>
                </nav>
            </div>
        </header><!-- #header-->

        <section id="middle">
            <?php echo $this->content; ?>
        </section><!-- #middle-->

        <footer id="footer">
            <div class="footer_block">
                <?php $dateTime = new DateTime('now'); ?>
                &copy; 2007-<?php echo $dateTime->format('Y'); ?> Jhekasoft
            </div>
        </footer><!-- #footer -->

    </div><!-- #wrapper -->
    <?php echo $this->inlineScript() ?>
</body>
</html>
