<?php echo $this->doctype(); ?>

<html>
<head>
    <meta charset="utf-8" />
    <?php echo $this->headTitle($this->translate('Jhekasoft'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta(); ?>

    <?php //echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/js/chosen/chosen.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/functions.js')
                                  ->prependFile($this->basePath() . '/js/chosen/chosen.jquery.min.js')
                                  ->prependFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'IE',))
                                  ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js') ?>

    <?php /* ?><script>
        $(window).load(function() {
            $('#sideRight').css('height', $('#content').outerHeight())
        });

        $(window).resize(function() {
            $('#sideRight').css('height', $('#content').outerHeight())
        });
    </script><?php */ ?>

    <script>
        $(document).ready(function() {
            $(".chzn-select-deselect").chosen({
                no_results_text: "Нет результатов для",
                allow_single_deselect: true
            });
        });
    </script>

    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35700833-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter20852641 = new Ya.Metrika({id:20852641,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/20852641" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</head>

<body id="body_top">

    <div id="wrapper">

        <header id="header">
            <div class="nav_block">
                <nav class="nav_block_main">
                    <div class="nav_block_logo">
                        <a href="<?php echo $this->url('home'); ?>" class="nav_block_logo_link">Jhekasoft</a>
                    </div>
                    <ul class="nav_block_main_menu">
                        <li>
                            <a href="<?php echo $this->url('software/default'); ?>"><?php echo $this->translate('Software'); ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('software/default', array('type' => 'game')); ?>"><?php echo $this->translate('Games'); ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('video'); ?>"><?php echo $this->translate('Video'); ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('bilet33'); ?>"><?php echo $this->translate('Sound'); ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('blog'); ?>"><?php echo $this->translate('Blog'); ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('about'); ?>"><?php echo $this->translate('About'); ?></a>
                        </li>
                        <li class="nav_block_main_menu_end">
                            <span>&nbsp;</span>
                        </li>
                    </ul>
                </nav>
                <div class="clr"></div>
            </div>
        </header><!-- #header-->

        <section id="middle">
            <?php echo $this->content; ?>
            <?php echo $this->gotoTop(); ?>
        </section><!-- #middle-->

        <footer id="footer">
            <div class="footer_block">
                <?php $dateTime = new DateTime('now'); ?>
                &copy; 2007-<?php echo $dateTime->format('Y'); ?> <a href="<?php echo $this->url('about'); ?>">Jhekasoft</a>
            </div>
        </footer><!-- #footer -->

    </div><!-- #wrapper -->
    <?php echo $this->inlineScript() ?>
</body>
</html>
