<?php if ($this->pageCount > 1) { ?>
    <div class="pagination_control">
        <!-- Previous page link -->
        <?php if (isset($this->previous)) { ?>
            <a href="<?php echo $this->url($this->route, array('page' => $this->previous), array(), true); ?>" class="paginator_arrow">&larr;</a>
        <?php } else { ?>
            <span class="paginator_arrow paginator_arrow_disabled">&larr;</span>
        <?php }; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page) { ?>
            <?php if ($page != $this->current) { ?>
                <a href="<?php echo $this->url($this->route, array('page' => $page), array(), true); ?>" class="paginator_page"><?php echo $page; ?></a>
            <?php } else { ?>
                <span class="paginator_page paginator_page_active"><?php echo $page; ?></span>
            <?php }; ?>
        <?php }; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)) { ?>
            <a href="<?php echo $this->url($this->route, array('page' => $this->next), array(), true); ?>" class="paginator_arrow">&rarr;</a>
        <?php } else { ?>
            <span class="paginator_arrow paginator_arrow_disabled">&rarr;</span>
        <?php }; ?>
    </div>
<?php }; ?>
