<?php if ($this->pageCount > 1) { ?>
    <div class="pagination_control">
        <!-- Previous page link -->
        <?php if (isset($this->previous)) { ?>
            <a href="<?php echo $this->url($this->route, array('page' => $this->previous), array(), true); ?>">&larr;</a>
        <?php } else { ?>
            <span class="disabled">&larr;</span>
        <?php }; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page) { ?>
            <?php if ($page != $this->current) { ?>
                <a href="<?php echo $this->url($this->route, array('page' => $page), array(), true); ?>"><?php echo $page; ?></a>
            <?php } else { ?>
                <?php echo $page; ?>
            <?php }; ?>
        <?php }; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)) { ?>
            <a href="<?php echo $this->url($this->route, array('page' => $this->next), array(), true); ?>">&rarr;</a>
        <?php } else { ?>
            <span class="disabled">&rarr;</span>
        <?php }; ?>
    </div>
<?php }; ?>
