<?php
$title = $this->translate('Pages');
$this->headTitle($title);
?>

<div id="container">
    <div id="content">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        
        <div>
            <?php if (count($this->paginator) > 0) { ?>
                <?php echo $this->partialLoop('pages/pages/index-item.phtml', $this->paginator) ?>
            <?php } else { ?>
                <p>Извините, автор ещё не добавил странички.</p>
            <?php } ?>
        </div>
        
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml', array('route' => 'pages/default')); ?>
    </div><!-- #content-->
</div><!-- #container-->

<?php echo $this->sideLeft(); ?>
