<?php
$title = $item->title . ' ' . $item->version;
$this->headTitle($title);
$this->headMeta()->appendName('description', $this->escapeHtml($item->meta_description_default))
                 ->appendName('keywords', $this->escapeHtml($item->meta_keywords));
?>

<div id="container">
    <div id="content">
        <?php if ($this->can_edit) { ?>
            <a href="<?php echo $this->url('pages/edit', array('name' => $item->name)); ?>">редактировать</a>
        <?php } ?>

        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <div>
            <?php echo $item->text; ?>
        </div>

        <?php if ('yes' == $item->show_share) { ?>
            <?php echo $this->shareBlock(); ?>
        <?php } ?>

        <?php if ('yes' == $item->show_comments) { ?>
            <div style="margin-top: 40px;">
                <?php echo $this->commentsBlock(); ?>
            </div>
        <?php } ?>
    </div><!-- #content-->
</div><!-- #container-->

<?php echo $this->sideRight(); ?>
