<?php
$title = $this->item->title;
$this->headTitle($title);
$this->headMeta()->appendName('description', $this->item->meta_description_default)
                 ->appendName('keywords', $this->item->meta_keywords);
?>

<div id="container">
    <div id="content">
        <?php if ($this->can_edit) { ?>
            <a href="<?php echo $this->url('pages/edit', array('name' => $this->item->name)); ?>">редактировать</a>
        <?php } ?>

        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <div>
            <?php echo $this->item->filtered_text; ?>
        </div>

        <?php if ('yes' == $this->item->show_share) { ?>
            <?php echo $this->shareBlock(); ?>
        <?php } ?>

        <?php if ('yes' == $this->item->show_comments) { ?>
            <div style="margin-top: 40px;">
                <?php echo $this->commentsBlock(); ?>
            </div>
        <?php } ?>
    </div><!-- #content-->
</div><!-- #container-->

<?php //echo $this->sideRight(); ?>
