<?php
    $datetime = new DateTime($this->datetime);
?>
<div class="blog_item_datetime_block">
    <?php if (!empty($this->image)) { ?>
        <a href="<?php echo $this->url('blog/show', array('name' => $this->name)); ?>">
            <img src="<?php echo $this->basePath(); ?>/files/blog/images/p_<?php echo $this->image; ?>" alt="" style="float: left; width: 140px; margin-right: 10px; margin-bottom: 10px;">
        </a>
    <?php } ?>
    <div>
        <a href="<?php echo $this->url('blog/show', array('name' => $this->name)); ?>"><?php echo $this->escapeHtml($this->title); ?></a>
        <span class="blog_item_datetime" ><?php echo $datetime->format('d.m.Y, H:i'); ?></span>
        <div class="blog_item_text">
            <?php echo $this->cut_text; ?>
            <div class="clr"></div>
            <a class="blog_item_show_link" href="<?php echo $this->url('blog/show', array('name' => $this->name)); ?>">Читать далее...</a>
        </div>
    </div>
    
    <div class="clr"></div>
</div>
