<?php
$title = $this->item->title;
$this->headTitle($title);
$this->headTitle('Блог');
$this->headMeta()->appendName('description', $this->item->meta_description_default)
                 ->appendName('keywords', $this->item->meta_keywords);

$datetime = new DateTime($this->item->datetime);
?>

<div id="container">
    <div id="content">
        <?php if ($this->can_edit) { ?>
            <a href="<?php echo $this->url('blog/edit', array('name' => $this->item->name)); ?>">редактировать</a>
        <?php } ?>

        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <div class="blog_item_datetime_show_block">
            <span class="blog_item_datetime_show"><?php echo $datetime->format('d.m.Y, H:i'); ?></span>
        </div>

        <div>
            <?php echo $this->item->text; ?>
        </div>

        <?php echo $this->shareBlock(); ?>

        <?php if ('yes' == $this->item->show_comments) { ?>
            <div style="margin-top: 40px;">
                <?php echo $this->commentsBlock(); ?>
            </div>
        <?php } ?>
    </div><!-- #content-->
</div><!-- #container-->

<?php //echo $this->sideRight(); ?>
