<div><?php echo $this->sound->author; ?> — <?php echo $this->sound->title; ?></div>
<audio controls>
    <source src="/files/audio/<?php echo $this->sound->file; ?>.mp3">
    <source src="/files/audio/<?php echo $this->sound->file; ?>.ogg">
    Тут должна была быть песенка(<a href="/files/audio/<?php echo $this->sound->file; ?>.mp3">mp3</a> |
    <a href="/files/audio/<?php echo $this->sound->file; ?>.ogg">ogg</a>). Но ваш браузер не смог её воспроизвести :(
</audio>
