<?php if (!empty($this->sound->lyrics)) { ?>
    <?php if(0) { ?><script><?php } ?>
    <?php $this->headScript()->captureStart() ?>
    $(document).ready(function() {
        $('.content_information_additional_<?php echo $this->sound->name; ?>').hide();
    });
    <?php $this->headScript()->captureEnd() ?>
    <?php if(0) { ?></script><?php } ?>
<?php } ?>

<div class="content_information">
    <div><?php echo $this->sound->author; ?> — <?php echo $this->sound->title; ?>
        <?php if (!empty($this->sound->lyrics)) { ?>
            | <a href="javascript:void(0);" onclick="$('.content_information_additional_<?php echo $this->sound->name; ?>').slideToggle();" class="no_href">текст</a>
        <?php } ?>
    </div>

    <audio controls>
        <source src="<?php echo $this->serverUrl() . $this->basePath('files/audio/' . $this->sound->file); ?>">
        <source src="<?php echo $this->serverUrl() . $this->basePath('files/audio/' . $this->sound->file2); ?>">
        <a href="<?php echo $this->serverUrl() . $this->basePath('files/audio/' . $this->sound->file); ?>">mp3</a> |
        <a href="<?php echo $this->serverUrl() . $this->basePath('files/audio/' . $this->sound->file2); ?>">ogg</a>
    </audio>

    <?php if (!empty($this->sound->lyrics)) { ?>
        <div class="content_information_additional content_information_additional_<?php echo $this->sound->name; ?>">
            <?php echo $this->sound->lyrics; ?>
        </div>
    <?php } ?>
</div>
