<?php if (!empty($this->sound->lyrics)) { ?>
    <?php if(0) { ?><script><?php } ?>
    <?php $this->headScript()->captureStart() ?>
    $(document).ready(function() {
        $('.content_information_additional_<?php echo $this->sound->name; ?>').hide();
    });
    <?php $this->headScript()->captureEnd() ?>
    <?php if(0) { ?></script><?php } ?>
<?php } ?>

<div class="content_information">
    <div><?php echo $this->sound->author; ?> — <?php echo $this->sound->title; ?>
        <?php if (!empty($this->sound->lyrics)) { ?>
            | <a href="javascript:void(0);" onclick="$('.content_information_additional_<?php echo $this->sound->name; ?>').slideToggle();" class="no_href">текст</a>
        <?php } ?>
    </div>

    <audio controls>
        <source src="/files/audio/<?php echo $this->sound->file; ?>.mp3">
        <source src="/files/audio/<?php echo $this->sound->file; ?>.ogg">
        Тут должна была быть песенка(<a href="/files/audio/<?php echo $this->sound->file; ?>.mp3">mp3</a> |
        <a href="/files/audio/<?php echo $this->sound->file; ?>.ogg">ogg</a>). Но ваш браузер не смог её воспроизвести :(
    </audio>

    <?php if (!empty($this->sound->lyrics)) { ?>
        <div class="content_information_additional content_information_additional_<?php echo $this->sound->name; ?>">
            <?php echo $this->sound->lyrics; ?>
        </div>
    <?php } ?>
</div>
