<aside id="sideLeft">
    <form class="filter_form" name="" action="" method="">
        <div class="filter_form_element_item">
            <select class="chzn-select-deselect" name="test" data-placeholder="Тип" style="width: 230px;">
                <option value=""></option>
                <option value="1">Приложение</option>
                <option value="2">Игра</option>
            </select>
        </div>
        <div class="filter_form_element_item">
            <select class="chzn-select-deselect" name="test" data-placeholder="Платформа" style="width: 230px;">
                <option value=""></option>
                <option value="1">WWW</option>
                <option value="2">GNU/Linux</option>
                <option value="3">Android</option>
                <option value="4">Windows</option>
            </select>
        </div>
        <div class="filter_form_element_item">
            <select class="chzn-select-deselect" name="test" data-placeholder="Автор" style="width: 230px;">
                <option value=""></option>
                <option value="1">Евгений Ефремов (Jhekasoft)</option>
                <option value="2">Александр Дадыка</option>
                <option value="3">Юрий Исаев</option>
            </select>
        </div>
        <div class="filter_form_element_item">
            <a href="#" class="filter_form_cancel_link">Сбросить</a>
            <input type="submit" name="filter_form_submit" value="Фильтровать" class="filter_form_submit" style="float: right;">
        </div>
    </form>
</aside><!-- #sideLeft -->