<div class="coming_soon_block">
    <h1 class="coming_soon_title">Jhekasoft</h1>
    
    <?php echo $this->finalCountdown($endDatetime); ?>
    
    <div class="coming_soon_middle">
        <p>Скоро сайт запустится.</p>
        <p>И тогда всё сбудется.</p>
        <p>А пока, чтоб не грустить,</p>
        <p>Лезь про Арч <a href="http://www.jappix.com/?r=instead@conference.jabber.ru">сюда</a> поныть.</p>
        
        <p>&nbsp;</p>
        
        <p>Хочешь квестик ты пройти?</p>
        <p>Так тогда тебе <a href="http://instead.syscall.ru/games/">сюды</a>.</p>
        <p>Хочешь квестик написать?</p>
        <p><a href="http://instead.syscall.ru/2012/10/insteadoz1/">Здесь</a> тебе помогут, брат!</p>
        
        <p>&nbsp;</p>
        
        <p class="coming_soon_copyright">&copy; <a href="https://www.google.com.ua/search?q=jhekasoft">Jhekasoft</a></p>
    </div>
</div>
