<?php $this->headLink()
            ->appendStylesheet($this->basePath() . '/css/coming-soon.css')
?>

<div class="coming_soon_block">
    <h1 class="coming_soon_title">Jhekasoft</h1>
    
    <?php echo $this->finalCountdownBlock($this->endDatetime); ?>
    
    <div class="coming_soon_middle">
        <p>Скоро сайт запустится.</p>
        <p>И тогда всё сбудется.</p>
        <p>А пока, чтоб не грустить,</p>
        <p>Лезь про Арч <a href="http://www.jappix.com/?r=instead@conference.jabber.ru">сюда</a> поныть.</p>
        
        <p>&nbsp;</p>
        
        <p>Хочешь квестик ты пройти?</p>
        <p>Так тогда тебе <a href="http://instead.syscall.ru/games/">сюды</a>.</p>
        <p>Хочешь квестик написать?</p>
        <p><a href="http://instead.syscall.ru/2012/10/insteadoz1/">Здесь</a> тебе помогут, брат!</p>
        
        <div style="margin-top: 40px;">
            <audio controls>
              <source src="<?php echo $this->basePath(); ?>/upload/audio/bilet33/about_encodings.mp3">
              <source src="<?php echo $this->basePath(); ?>/upload/audio/bilet33/about_encodings.ogg">
              Тут должна была быть песенка(<a href="<?php echo $this->basePath(); ?>/upload/audio/bilet33/about_encodings.mp3">mp3</a> |
              <a href="<?php echo $this->basePath(); ?>/upload/audio/bilet33/about_encodings.ogg">ogg</a>). Но ваш браузер не смог её воспроизвести :(
            </audio>
        </div>
        
        <?php echo $this->likeBlock(); ?>
        
        <p class="coming_soon_copyright">&copy; <a href="https://www.google.com.ua/search?q=jhekasoft">Jhekasoft</a></p>
    </div>
</div>
