<?php if(0) { ?><script><?php } ?>
<?php $this->headScript()->captureStart() ?>    
    var FinalCountdown = {
        timer : null,
        minutes : 0,
        seconds : 0,
        
        /*
         * Получает значение оставшегося времени
         */
        getLeftTime : function() {
            clearTimeout(FinalCountdown.timer);
            
            $.getJSON("<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'ajax-get-left-time')) ?>", {
            },
            function(response){
                if(response.leftTime) {
                    $('.finalcountdown_days').text(response.leftTime.days);
                    $('.finalcountdown_hours').text(response.leftTime.hours);
                    $('.finalcountdown_minutes').text(response.leftTime.minutes);
                    $('.finalcountdown_seconds').text(response.leftTime.seconds);
                    
                    $('.finalcountdown_label_days').text(Functions.pluralWord(response.leftTime.days, ['день', 'дня', 'дней']));
                    $('.finalcountdown_label_hours').text(Functions.pluralWord(response.leftTime.hours, ['час', 'часа', 'часов']));
                    $('.finalcountdown_label_minutes').text(Functions.pluralWord(response.leftTime.minutes, ['минута', 'минуты', 'минут']));
                    $('.finalcountdown_label_seconds').text(Functions.pluralWord(response.leftTime.seconds, ['секунда', 'секунды', 'секунд']));
                    
                    FinalCountdown.minutes = response.leftTime.minutes;
                    FinalCountdown.seconds = response.leftTime.seconds;

                    // Если время ещё не закончилось, то возобновляем отсчёт
                    // Иначе показываем стартовый блок
                    if(!response.leftTime.isEnd) {
                        FinalCountdown.timer = setTimeout(FinalCountdown.updateLeftTime, 1000);
                    } else {
                        FinalCountdown.showStartBlock();
                    }
                }
            });
        },
        
        /*
         * Обновляет значение оставшегося времени
         */
        updateLeftTime : function() {
            FinalCountdown.seconds--; // уменьшаем секунды
            
            if(FinalCountdown.seconds < 0) {
                FinalCountdown.seconds = 59;
                FinalCountdown.minutes--; // уменьшаем минуты
            }
            
            // Получаем значение оставшегося времени
            // или выводим просчитанное с помощью JS
            if(FinalCountdown.minutes < 0) {
                FinalCountdown.getLeftTime();
            } else {
                $('.finalcountdown_minutes').text(FinalCountdown.minutes);
                $('.finalcountdown_seconds').text(FinalCountdown.seconds);
                
                $('.finalcountdown_label_minutes').text(Functions.pluralWord(FinalCountdown.minutes, ['минута', 'минуты', 'минут']));
                $('.finalcountdown_label_seconds').text(Functions.pluralWord(FinalCountdown.seconds, ['секунда', 'секунды', 'секунд']));
                FinalCountdown.timer = setTimeout(FinalCountdown.updateLeftTime, 1000);
            }
        },
        
        showStartBlock : function() {
            $.getJSON("<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'ajax-get-start-link')) ?>", {
            },
            function(response) {
                $('a.coming_soon_start_link').attr('href', response.link);
                
                $('.coming_soon_finalcountdown').fadeOut(1000, function() {
                    $('.coming_soon_start').fadeIn(1000);
                });
            });
        },
        
        showEmailPopup : function() {
            $('.finalcountdown_email').slideDown();
        },
        
        hideEmailPopup : function() {
            $('.finalcountdown_email').fadeOut();
        },
        
        addEmail : function() {
            $('.popup_form_error_email').hide();
            
            if(Functions.isValidEmail($('input[name=email]').val())) {
                $.getJSON("<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'ajax-save-final-countdown-email')) ?>", {
                    email : $('input[name=email]').val()
                },
                function(response) {
                    if('ok' == response.status) {
                        $('.email_form').hide();

                        $('.email_send_holder').text(response.email);
                        $('.email_sent').show();
                    }
                });
            } else {
                $('.popup_form_error_email').show();
            }
        }
    };

    $(document).ready(function() {
        FinalCountdown.updateLeftTime();
        
        $(".finalcountdown_email_popup").draggable({handle: '.finalcountdown_email_popup_head'});
    });
<?php $this->headScript()->captureEnd() ?>
<?php if(0) { ?></script><?php } ?>

<div class="coming_soon_finalcountdown" onclick="FinalCountdown.showEmailPopup();">
    <span class="finalcountdown_number finalcountdown_days"><?php echo $this->leftTime['days']; ?></span>
    <span class="finalcountdown_label finalcountdown_label_days"><?php echo $this->leftTime['daysLabel']; ?></span>&nbsp;
    
    <span class="finalcountdown_number finalcountdown_hours"><?php echo $this->leftTime['hours']; ?></span>
    <span class="finalcountdown_label finalcountdown_label_hours"><?php echo $this->leftTime['hoursLabel']; ?></span>&nbsp;
    
    <span class="finalcountdown_number finalcountdown_minutes"><?php echo $this->leftTime['minutes']; ?></span>
    <span class="finalcountdown_label finalcountdown_label_minutes"><?php echo $this->leftTime['minutesLabel']; ?></span>&nbsp;
    
    <span class="finalcountdown_number finalcountdown_seconds"><?php echo $this->leftTime['seconds']; ?></span>
    <span class="finalcountdown_label finalcountdown_label_seconds"><?php echo $this->leftTime['secondsLabel']; ?></span>
    
    <div class="finalcountdown_about">
        <div class="finalcountdown_about_text_block popup_block">
            <a class="no_href" href="javascript: void(0);" onclick="FinalCountdown.showEmailPopup();">Как не пропустить грандиозное открытие?</a>
        </div>
    </div>
</div>

<div class="finalcountdown_email">
    <div class="finalcountdown_email_popup popup_block">
        <div class="finalcountdown_email_popup_head popup_head">
            <h2>Оставьте свой Email</h2>
            <span class="popup_head_close"><a href="javascript: void(0);" onclick="FinalCountdown.hideEmailPopup();"><img src="<?php echo $this->basePath(); ?>/images/close.png" alt="x"></a></span>
        </div>
        
        <div class="popup_body">
            <form class="email_form" action="" method="post">
                <p>
                    Вам придёт напоминание за час до открытия сайта.
                    Спамить не буду, только одно сообщение :)
                </p>
                <p>
                    <input type="text" name="email" placeholder="Ваш Email">
                    <span class="popup_form_error popup_form_error_email" style="display: none;">Введите корректный Email</span>
                </p>
                <p>
                    <input type="submit" value="Напомни мне" onclick="FinalCountdown.addEmail(); return false;">
                    <input type="submit" value="Отстань" onclick="FinalCountdown.hideEmailPopup(); return false;">
                </p>
            </form>

            <form class="email_sent" action="" method="post" style="display: none;">
                <p>
                    Спасибо за проявленный интерес!
                    За час до открытия сайта на ваш ящик <span class="email_send_holder"></span> придёт напоминание.
                </p>
                <p>
                    <input type="submit" value="И тебе спасибки" onclick="FinalCountdown.hideEmailPopup(); return false;">
                </p>
            </form>
        </div>
    </div>
</div>

<div class="coming_soon_start" style="display: none;">
    <a class="coming_soon_start_link" href="#">Старт &rarr;</a>
</div>
