<?php if(0) { ?><script><?php } ?>
<?php $this->headScript()->captureStart() ?>    
    var FinalCountdown = {
        timer : null,
        minutes : 0,
        seconds : 0,
        
        /*
         * Получает значение оставшегося времени
         */
        getLeftTime : function() {
            clearTimeout(FinalCountdown.timer);
            
            $.getJSON("<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'ajax-get-left-time')) ?>", {
            },
            function(response){
                if(response.leftTime) {
                    $('.finalcountdown_days').text(response.leftTime.days);
                    $('.finalcountdown_hours').text(response.leftTime.hours);
                    $('.finalcountdown_minutes').text(response.leftTime.minutes);
                    $('.finalcountdown_seconds').text(response.leftTime.seconds);
                    
                    $('.finalcountdown_label_days').text(Functions.pluralWord(response.leftTime.days, ['день', 'дня', 'дней']));
                    $('.finalcountdown_label_hours').text(Functions.pluralWord(response.leftTime.hours, ['час', 'часа', 'часов']));
                    $('.finalcountdown_label_minutes').text(Functions.pluralWord(response.leftTime.minutes, ['минута', 'минуты', 'минут']));
                    $('.finalcountdown_label_seconds').text(Functions.pluralWord(response.leftTime.seconds, ['секунда', 'секунды', 'секунд']));
                    
                    FinalCountdown.minutes = response.leftTime.minutes;
                    FinalCountdown.seconds = response.leftTime.seconds;

                    // Если время ещё не закончилось, то возобновляем отсчёт
                    // Иначе показываем стартовый блок
                    if(!response.leftTime.isEnd) {
                        FinalCountdown.timer = setTimeout(FinalCountdown.updateLeftTime, 1000);
                    } else {
                        FinalCountdown.showStartBlock();
                    }
                }
            });
        },
        
        /*
         * Обновляет значение оставшегося времени
         */
        updateLeftTime : function() {
            FinalCountdown.seconds--; // уменьшаем секунды
            
            if(FinalCountdown.seconds < 0) {
                FinalCountdown.seconds = 59;
                FinalCountdown.minutes--; // уменьшаем минуты
            }
            
            // Получаем значение оставшегося времени
            // или выводим просчитанное с помощью JS
            if(FinalCountdown.minutes < 0) {
                FinalCountdown.getLeftTime();
            } else {
                $('.finalcountdown_minutes').text(FinalCountdown.minutes);
                $('.finalcountdown_seconds').text(FinalCountdown.seconds);
                
                $('.finalcountdown_label_minutes').text(Functions.pluralWord(FinalCountdown.minutes, ['минута', 'минуты', 'минут']));
                $('.finalcountdown_label_seconds').text(Functions.pluralWord(FinalCountdown.seconds, ['секунда', 'секунды', 'секунд']));
                FinalCountdown.timer = setTimeout(FinalCountdown.updateLeftTime, 1000);
            }
        },
        
        showStartBlock : function() {
            $.getJSON("<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'ajax-get-start-link')) ?>", {
            },
            function(response) {
                $('a.coming_soon_start_link').attr('href', response.link);
                
                $('.coming_soon_finalcountdown').fadeOut(1000, function() {
                    $('.coming_soon_start').fadeIn(1000);
                });
            });
        }
    };

    $(document).ready(function() {
        FinalCountdown.updateLeftTime();
    });
<?php $this->headScript()->captureEnd() ?>
<?php if(0) { ?></script><?php } ?>

<div class="coming_soon_finalcountdown">
    <span class="finalcountdown_number finalcountdown_days"><?php echo $this->leftTime['days']; ?></span>
    <span class="finalcountdown_label finalcountdown_label_days"><?php echo $this->leftTime['daysLabel']; ?></span>&nbsp;
    
    <span class="finalcountdown_number finalcountdown_hours"><?php echo $this->leftTime['hours']; ?></span>
    <span class="finalcountdown_label finalcountdown_label_hours"><?php echo $this->leftTime['hoursLabel']; ?></span>&nbsp;
    
    <span class="finalcountdown_number finalcountdown_minutes"><?php echo $this->leftTime['minutes']; ?></span>
    <span class="finalcountdown_label finalcountdown_label_minutes"><?php echo $this->leftTime['minutesLabel']; ?></span>&nbsp;
    
    <span class="finalcountdown_number finalcountdown_seconds"><?php echo $this->leftTime['seconds']; ?></span>
    <span class="finalcountdown_label finalcountdown_label_seconds"><?php echo $this->leftTime['secondsLabel']; ?></span>
</div>

<div class="coming_soon_start" style="display: none;">
    <a class="coming_soon_start_link" href="#">Старт &rarr;</a>
</div>
