<div class="like_block">
    <div style="display: inline-block;">
        <iframe src="//www.facebook.com/plugins/like.php?href=<?php echo urlencode($this->url(null, array(), array('force_canonical' => true))); ?>&amp;send=false&amp;layout=button_count&amp;width=160&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=216103491782380" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:160px; height:21px;" allowTransparency="true"></iframe>
    </div>

    <div class="like_block_item">
        <!-- Put this script tag to the <head> of your page -->
        <script type="text/javascript" src="//vk.com/js/api/openapi.js?60"></script>

        <script type="text/javascript">
            VK.init({apiId: 3187769, onlyWidgets: true});
        </script>

        <!-- Put this div tag to the place, where the Like block will be -->
        <div id="vk_like"></div>
        <script type="text/javascript">
            VK.Widgets.Like("vk_like", {type: "mini"});
        </script>
    </div>

    <div class="like_block_item">
        <a href="https://twitter.com/share" class="twitter-share-button" data-lang="ru" data-hashtags="jhekasoft">Твитнуть</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>

    <div class="like_block_item">
        <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
        <g:plusone></g:plusone>
    </div>
</div>