<div style="margin-top: 20px; background: #F9FAFA; border: 1px solid #ccc; border-radius: 5px;">
    <div style="float: right;">
        <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
        <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter"></div> 
    </div>
    <div class="clr"></div>
</div>