<aside id="sideLeft">
    <strong>Left Sidebar:</strong> Integer velit. Vestibulum nisi nunc, accumsan ut, vehicula sit amet, porta a, mi. Nam nisl tellus, placerat eget, posuere eget, egestas eget, dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In elementum urna a eros. Integer iaculis. Maecenas vel elit.
    <?php echo $this->test; ?>
    
    <div style="margin-top: 20px;">
        <select class="chzn-select-deselect" name="test" data-placeholder="Выберите тип..." style="width: 230px;">
            <option value=""></option>
            <option value="1">Опция 1</option>
            <option value="2">Опция 2</option>
            <option value="3">Опция 3</option>
        </select>
    </div>
</aside><!-- #sideLeft -->