<aside id="sideRight">
    <p>Новогодняя песня!</p>
    <p><a href="<?php echo $this->url('sound'); ?>">Билет 33 — Новый год</a></p>
    
    <div class="goto_top_block" onclick="Functions.goToTop();">
        <div class="goto_top_link_container">
            <a class="goto_top_imglink" href="#body_top" onclick="return false;">
                <span class="goto_top_img">&nbsp;</span></a>
            <br>
            <a class="goto_top_link" href="#body_top" onclick="return false;">Вверх</a>
        </div>
    </div>
</aside><!-- #sideRight -->

<div style="text-align: left;">
    <img src="<?php echo $this->basePath(); ?>/images/cat.png" alt="Кошка" style="margin-top: 20px; margin-left: 10px;">
</div>