<?php if (0) { ?><script><?php } ?>
<?php $this->inlineScript()->captureStart() ?>
if(!/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)) {
	$(document).ready(function() {
		$('#header').css('width', 1000);
		$('#header').css('background-color', '#fff');
		$('#header').css('z-index', 100);

		$(window).scroll(function () {
			if ($(this).scrollTop() > 10) {
				$('#header').css('position', 'fixed');
				//$('#header .nav_block').css('margin-top', 0);
				$('#middle').css('padding-top', 62);

				console.log('show');
			} else {
				$('#header').css('position', '');
				//$('#header .nav_block').css('margin-top', 10);
				$('#middle').css('padding-top', '');

				console.log('hide');
			}
		});
	});
}
<?php $this->inlineScript()->captureEnd() ?>
<?php if (0) { ?></script><?php } ?>
