<?php if (0) { ?><script><?php } ?>
<?php $this->inlineScript()->captureStart() ?>
if(!/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)) {
	$(document).ready(function() {
		$('#header').css('width', 1000);
		$('#header').css('background-color', '#fff');
		$('#header').css('z-index', 100);

		$('#header').css('position', 'fixed');
		//$('#header .nav_block').css('margin-top', 0);
		$('#middle').css('padding-top', 60);
	});
}
<?php $this->inlineScript()->captureEnd() ?>
<?php if (0) { ?></script><?php } ?>
